"""Added graduation year

Revision ID: 204baaa49d5b
Revises: 5578a65f7629
Create Date: 2023-08-14 19:18:09.175689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204baaa49d5b'
down_revision = '5578a65f7629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('graduation_year')

    # ### end Alembic commands ###
