"""create db

Revision ID: 311869031052
Revises: 
Create Date: 2023-08-02 17:31:12.362031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311869031052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('deletion_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_second_name'), ['second_name'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deskid', sa.Integer(), nullable=False),
    sa.Column('bookerId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['bookerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deskid'], ['desk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_second_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))

    op.drop_table('user')
    op.drop_table('desk')
    # ### end Alembic commands ###
