"""Added desks deletion date

Revision ID: 4f39105474e6
Revises: 311869031052
Create Date: 2023-08-05 11:17:17.190598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f39105474e6'
down_revision = '311869031052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletion_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.drop_column('deletion_date')

    # ### end Alembic commands ###
